pub const AMOUNT_OUT_OF_RANGE: felt252 = 'ZT_AMOUNT_TOO_LARGE';
pub const INVALID_BURN_AMOUNT: felt252 = 'ZT_INVALID_BURN_AMOUNT';
pub const INVALID_COLLATERALIZATION: felt252 = 'ZT_INVALID_COLLATERALIZATION';
pub const INVALID_MINT_AMOUNT: felt252 = 'ZT_INVALID_MINT_AMOUNT';
pub const INVALID_TRANSFER_AMOUNT: felt252 = 'ZT_INVALID_TRANSFER_AMOUNT';
pub const MINT_TO_ZERO: felt252 = 'ZT_MINT_TO_ZERO';
pub const NOT_MARKET: felt252 = 'ZT_NOT_MARKET';
pub const ZERO_ADDRESS: felt252 = 'ZT_ZERO_ADDRESS';
